WITH CTE01_daily_weather AS (


    SELECT
    
    DATE(TIME) AS DAILY_WEATHER,
    WEATHER,
    TEMP,
    PRESSURE,
    HUMIDITY,
    CLOUDS

    FROM {{ source('demo', 'WEATHER_EXTRACTED') }}



),

CTE02_DAILY_WEATHER_AGGR AS (

SELECT
    DAILY_WEATHER,
    WEATHER,
    ROUND(AVG(TEMP),2) AS TEMP_AVG,
    ROUND(AVG(PRESSURE),2) AS PRESSURE_AVG,
    ROUND(AVG(HUMIDITY),2) AS HUMIDITY_AVG,
    ROUND(AVG(CLOUDS),2) AS CLOUDS_AVG


FROM CTE01_daily_weather
GROUP BY DAILY_WEATHER, WEATHER
QUALIFY ROW_NUMBER() OVER (PARTITION BY DAILY_WEATHER ORDER BY COUNT(WEATHER) DESC) = 1

)

SELECT 
*
FROM CTE02_DAILY_WEATHER_AGGR