WITH CTE01_BIKE AS (


SELECT
    DISTINCT
    START_STATIO_ID AS STATION_ID,
    START_STATION_NAME AS STATION_NAME,
    -- END_STATION_NAME,
    START_LAT AS STATION_LAT,
    START_LNG AS STATION_LNG

FROM {{ ref('stg_bike') }}
WHERE RIDE_ID != 'ride_id'


)

SELECT 
    *
FROM CTE01_BIKE